### ISSUE TITLE
Present about the use of Event-State Carried Transfer

### ISSUE THREAD

**Issue by igakigongo** [igakigongo/js-tic-tac-toe#2]

**Comment by ghost** [comment]
[Odin project requirement]
![image](https://user-images.githubusercontent.com/40674031/72879067-7b5abe80-3d3f-11ea-91e5-d66279558f75.png)
[Microverse pathright requirement]
![image](https://user-images.githubusercontent.com/40674031/72879094-8ca3cb00-3d3f-11ea-8ee1-5b27c1c85206.png)
@igakigongo If you carefully read the requirement, you could update those parts.

**Comment by ghost** [comment]
@igakigongo And you may need to add "README#getting started" section to direct people to execute your program locally after cloning this repository.
You could have a look at this template.
https://github.com/microverseinc/readme-template

**Comment by grace-mugoiri** [comment]
Also maybe you can draw a demonstration board and add in readme to showcase how the board looks like.
Otherwise it looks okay, if the project is complete maybe merge everything to master(if you choose to)
